

###
GET http://192.168.100.22:4000/api/producto/getProductos HTTP/1.1

###
GET http://192.168.100.22:4000/api/producto/getProducto/2 HTTP/1.1

###
POST  http://192.168.100.22:4000/api/producto/addProducto HTTP/1.1
Content-Type: application/json

{
    "idProducto": 0,
    "nombreProducto": "Envase 20lt",
    "descripcionProducto": "Envase PET vacío de 20 LTS",
    "precio": 3000,
    "stock": 12,
    "activo": true
}

###
PUT  http://192.168.100.22:4000/api/producto/2 HTTP/1.1
Content-Type: application/json

{
    "nombreProducto": "Dispensador USB",
    "descripcionProducto": "Bomba dispensadora de agua recargable por USB",
    "precio": 5000,
    "stock": 100,
    "activo": true
}

###
DELETE  http://192.168.100.22:4000/api/producto/8
Content-Type: application/json
